version: '3'
services:
  webserver:
    image: nginx:alpine # Официальный образ Nginx
    ports:
      - "8011:80"       # Открываем внешний порт 8011, внутри контейнера работает на 80
    volumes:
      - .:/usr/share/nginx/html # Монтируем текущую папку в директорию сайта
    restart: always     # Перезагружается автоматически при падении